/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'surface-container-low': '#f1f5ed',
        'on-primary-container': '#88d494',
        'error': '#ba1a1a',
        'outline-variant': '#bfc9bd',
        'surface': '#f7fbf3',
        'on-tertiary-fixed': '#400013',
        'on-primary-fixed': '#00210a',
        'surface-tint': '#206c37',
        'outline': '#707a6f',
        'on-tertiary-container': '#ffacb9',
        'on-secondary': '#ffffff',
        'inverse-on-surface': '#eef2ea',
        'on-secondary-fixed-variant': '#00522d',
        'tertiary-fixed': '#ffd9dd',
        'inverse-surface': '#2d322d',
        'on-surface': '#181d18',
        'tertiary': '#691e30',
        'on-background': '#181d18',
        'on-primary-fixed-variant': '#005323',
        'primary-fixed-dim': '#8cd897',
        'on-error-container': '#93000a',
        'primary': '#00431b',
        'on-primary': '#ffffff',
        'on-tertiary': '#ffffff',
        'on-error': '#ffffff',
        'on-secondary-container': '#047240',
        'secondary': '#006d3d',
        'surface-variant': '#e0e4dc',
        'tertiary-container': '#863546',
        'secondary-fixed-dim': '#7ed99e',
        'surface-container-high': '#e6e9e2',
        'on-secondary-fixed': '#00210f',
        'on-tertiary-fixed-variant': '#7a2c3d',
        'surface-container-lowest': '#ffffff',
        'primary-container': '#0b5d2a',
        'surface-bright': '#f7fbf3',
        'error-container': '#ffdad6',
        'surface-container-highest': '#e0e4dc',
        'surface-dim': '#d7dbd4',
        'inverse-primary': '#8cd897',
        'background': '#f7fbf3',
        'secondary-fixed': '#9af6b8',
        'on-surface-variant': '#404940',
        'surface-container': '#ebefe7',
        'secondary-container': '#97f3b5',
        'primary-fixed': '#a7f4b1',
        'tertiary-fixed-dim': '#ffb2bd',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '24px',
        full: '9999px',
      },
      spacing: {
        xs: '0.5rem',
        lg: '3rem',
        xl: '5rem',
        base: '8px',
        gutter: '24px',
        sm: '1rem',
        'container-max': '1280px',
        md: '1.5rem',
      },
      fontFamily: {
        'headline-md': ['Poppins', 'sans-serif'],
        'display-lg': ['Poppins', 'sans-serif'],
        'display-xl': ['Poppins', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'headline-sm': ['Poppins', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-md': ['32px', { lineHeight: '1.3', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '600' }],
        'display-xl': ['64px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-sm': ['24px', { lineHeight: '1.4', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
      },
      maxWidth: {
        'container-max': '1280px',
      },
    },
  },
  plugins: [],
}
